name: Deploy Evidence Staging

on:
  pull_request:
    branches:
      - main
    paths:
      - evidence/**

jobs:
  evidence-deploy-stg:
    uses: ./.github/workflows/deploy-evidence.yml
    with:
      gcp-project-id: mathews-mrr-stg
      gcp-workload-identity-provider: projects/398127736452/locations/global/workloadIdentityPools/github/providers/mathews-mrr
      gcp-service-account: evidence@mathews-mrr-stg.iam.gserviceaccount.com
      vercel-org-id: team_moFeFBoZI7YgB3mRzRw4hNuX
      vercel-project-id: prj_wDkLGCIiqumf27AEJFSPHsi7ljuy
      vercel-project-name: mathews-mrr-stg
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
